### ISSUE TITLE
Add more "simulating user input" functions

### ISSUE THREAD

**Issue by avh4** [avh4/elm-program-test#6]
- [x] enter text into and input field (and textarea) #8 
- [x] click SPA links (or other links?) #9 
- [x] check checkboxes #8 
- [x] select from option fields #16

**Comment by brookeangel** [comment]
select: See #16

**Comment by avh4** [comment]
Everything here is done!  Please open new issues if you think of new things to add.
